### ISSUE TITLE
I can't use the link

### ISSUE THREAD

**Issue by seeledu** [alicank/Translation-Augmented-LibriSpeech-Corpus#1]
Hello！ I am an Macau researcher， I can't  use the link you provided to download the dataset. Could you please give me a new link?

**Comment by alicank** [comment]
Hello,

I see, the platform that's responsible for sharing the dataset seems to be
down. (https://persyval-platform.imag.fr)
I've sent an e-mail to learn when it is going to be up. I'll be in contact.

Thanks, and sorry for the inconvenience

(If the server is not going to be up sometime soon, I will try to share the
dataset from another platform)

Best regards

Alican Kocabıyıkoğlu

**Comment by alicank** [comment]
Dataset platform is down momentarily. It will be up in the upcoming days. However, in order to request a download of the dataset you can send an e-mail to Anthony Hombiat <anthony.hombiat@univ-grenoble-alpes.fr>, by giving the name of the dataset in order to receive a link.
