### ISSUE TITLE
Cannot get access to the dataset link

### ISSUE THREAD

**Issue by Victorwz** [alicank/Translation-Augmented-LibriSpeech-Corpus#3]
Hi, I just want to try to run your training script. However, it seems like the database has been deleted. Meanwhile, when I try to open your provided dataset link, nothing can be found now. I am wondering if you are updating or upgrading the corpus? Or your server for storing the dataset has crushed?

**Comment by alicank** [comment]
Hi, it seems that the university data serving platform has changed the link:

Can you please try with the link below?
https://perscido.univ-grenoble-alpes.fr/datasets/DS91

**Comment by Victorwz** [comment]
> Hi, it seems that the university data serving platform has changed the link:
> 
> Can you please try with the link below? https://perscido.univ-grenoble-alpes.fr/datasets/DS91

I am sorry but the link still does not work. Your provided link requires the educational login. I am from Rutgers University, United States. But the website does not allow me to login and download the resources. Is there any other way I could get access to LibriSpeech En-Fr Augmented-Translation Corpus?
