### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by c60603** [alicank/Translation-Augmented-LibriSpeech-Corpus#5]
Hi, I want to download the LIBRI-TRANS dataset, but the url "https://persyval-platform.univ-grenoble-alpes.fr/DS91/detaildataset" is invalid. Can you give me the link to download the dataset? Thanks.

**Comment by alicank** [comment]
Hi, there is also the new link in the readme file. You can download the dataset on zenodo which is mostly available using the following url: https://zenodo.org/record/6482585#.Y97R_a2ZO3B
